version: "3.8"
services:
  redis:
    image: "redis:6.0.8-alpine"
    ports:
      - 6379:6379
  web:
    build: .
    environment:
      - FLASK_RUN_PORT=8000
      - FLASK_APP=ghibli.py
      - FLASK_CONFIG=production
    ports:
      - 8000:8000
